language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

matrix:
    allow_failures:
        - go: tip

install:
  - go get -t -v ./...

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
